version: "3.9"
services:
  snipe-it:
    image: kamencho/snipeit 
    env_file: my_env_file
    volumes:
      - /root/snipe_it:/config
    ports:
      - "443:443"
      - "80:80"
    networks:
      - snipe-it
networks:
  snipe-it: 
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.5.0/24

        #trigge18