# name: Docker Image CI

# on:
#   push:
#     branches: [ "master" ]
#     paths: 
#       - 'app/dockerfiles/**'
#   pull_request:
#     branches: [ "change-test" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Login to Docker Hub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_TOKEN }}
#     - name: Build the SnipeIt Docker image
#       run: docker build -t kamencho/snipeit ./app/dockerfiles --file ./app/dockerfiles/Dockerfile 
#     - name: Push the new image to Docker Hub
#       run: docker push kamencho/snipeit
